- name: passing values form prompt
  hosts: web
  vars_prompt:
    - name: username
      prompt: enter your name
      private: false

    - name: password
      prompt: enter password
  tasks:
    - name: print the deatils
      ansible.builtin.debug:
        msg: "entered details name:{{username}}, password:{{password}}"