- name: install nginx and run nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: run nginx
      ansible.builtin.service:
        name: nahinx
        state: started
        enabled: yes

