- name: check nginx installed or not if not then install
  hosts: web
  become: yes
  tasks:
    - name:
      ansible.builtin.command: apt update -y

    - name: checking package
      ansible.builtin.shell: apt list --installed nginx
      register: varng
      ignore_errors: true

    - name: checking nginx
      ansible.builtin.shell: apt install nginx -y
      register: varsuc
      ignore_errors: yes
      when: varng.rc != 0

    - name: checking running nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: varsuc.rc == 0

    - name: installation is failed
      ansible.builtin.debug:
        msg: "installation is failed"
      when: var.suc != 0