- name: check servers status
  hosts: local
  connection: local
  become: yes
  vars_files:
    - resource.yaml
  tasks:
    - name: checking servers daily status
      ansible.builtin.command:
        - uptime | cat >> {{ uptime_file }}
        - df -h | cat >> {{ disk_usage }}
        - free -h | cat >> {{ memory_file }}